//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested content types are not supported. Types: {0}..
        /// </summary>
        internal static string ErrorRequestedContentTypesNotSupported {
            get {
                return ResourceManager.GetString("ErrorRequestedContentTypesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appSettings key is not found. Key name: {0}.
        /// </summary>
        internal static string ExceptionAppSettingsKeyNotFound {
            get {
                return ResourceManager.GetString("ExceptionAppSettingsKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNDEP PUT request failed. Error: {0}.
        /// </summary>
        internal static string ExceptionCndepPutRequestFailed {
            get {
                return ResourceManager.GetString("ExceptionCndepPutRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNDEP PUT request failed. Status: {0}; Description: {1}.
        /// </summary>
        internal static string ExceptionCndepPutRequestFailedDetails {
            get {
                return ResourceManager.GetString("ExceptionCndepPutRequestFailedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type is not supported. Type: {0}.
        /// </summary>
        internal static string ExceptionContentTypeNotSupported {
            get {
                return ResourceManager.GetString("ExceptionContentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating content parser instance. Content type: {0}; Error: {1}.
        /// </summary>
        internal static string ExceptionFailedCreatingContentParser {
            get {
                return ResourceManager.GetString("ExceptionFailedCreatingContentParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating IDeviceCommunicationHandler instance. Communication type: {0};  Error: {1}.
        /// </summary>
        internal static string ExceptionFailedCreatingIDeviceCommunicationHandlerInstance {
            get {
                return ResourceManager.GetString("ExceptionFailedCreatingIDeviceCommunicationHandlerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed obtaining sensor current data using CNDEP. Device id: {0}; Sensor id: {1}.
        /// </summary>
        internal static string ExceptionFailedObtainingSensorCurrentDataUsingCndep {
            get {
                return ResourceManager.GetString("ExceptionFailedObtainingSensorCurrentDataUsingCndep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed obtaining sensor current data using CNDEP. Device id: {0}; Sensor id: {1}; Status: {2}; Description: {3}.
        /// </summary>
        internal static string ExceptionFailedObtainingSensorCurrentDataUsingCndepDetails {
            get {
                return ResourceManager.GetString("ExceptionFailedObtainingSensorCurrentDataUsingCndepDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed obtaining sensor current data using HTTP REST. Device id: {0}; Sensor id: {1}.
        /// </summary>
        internal static string ExceptionFailedObtainingSensorCurrentDataUsingHttpRest {
            get {
                return ResourceManager.GetString("ExceptionFailedObtainingSensorCurrentDataUsingHttpRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed obtaining sensor current data using HTTP REST. Device id: {0}; Sensor id: {1}; Status: {2}; Description: {3}.
        /// </summary>
        internal static string ExceptionFailedObtainingSensorCurrentDataUsingHttpRestDetails {
            get {
                return ResourceManager.GetString("ExceptionFailedObtainingSensorCurrentDataUsingHttpRestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed retrieving sensor data from MSMQ message queue. Message queue name: {0}..
        /// </summary>
        internal static string ExceptionFailedRetrievingSensorDataFromMessageQueue {
            get {
                return ResourceManager.GetString("ExceptionFailedRetrievingSensorDataFromMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sending message to MSMQ message queue. Message queue name: {0}..
        /// </summary>
        internal static string ExceptionFailedSendingMessageToMessageQueue {
            get {
                return ResourceManager.GetString("ExceptionFailedSendingMessageToMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sending request to the output message queue. Message queue: {0}..
        /// </summary>
        internal static string ExceptionFailedSendingRequestToMessageQueue {
            get {
                return ResourceManager.GetString("ExceptionFailedSendingRequestToMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failing setting actuator value. Device id: {0}; Sensor id: {1}..
        /// </summary>
        internal static string ExceptionFailedSettingActuatorValueUsingCndep {
            get {
                return ResourceManager.GetString("ExceptionFailedSettingActuatorValueUsingCndep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed setting sensor current data using HTTP REST. Device id: {0}; Sensor id: {1}; Data: {2}.
        /// </summary>
        internal static string ExceptionFailedSettingSensorCurrentDataUsingHttpRest {
            get {
                return ResourceManager.GetString("ExceptionFailedSettingSensorCurrentDataUsingHttpRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed setting sensor current data using HTTP REST. Device id: {0}; Sensor id: {1}; Data: {2}; Status: {3}; Description: {4}.
        /// </summary>
        internal static string ExceptionFailedSettingSensorCurrentDataUsingHttpRestDetails {
            get {
                return ResourceManager.GetString("ExceptionFailedSettingSensorCurrentDataUsingHttpRestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP REST PUT request failed. Error: {0}.
        /// </summary>
        internal static string ExceptionHttpRestPutRequestFailed {
            get {
                return ResourceManager.GetString("ExceptionHttpRestPutRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP REST PUT request failed. Status: {0}; Description: {1}.
        /// </summary>
        internal static string ExceptionHttpRestPutRequestFailedDetails {
            get {
                return ResourceManager.GetString("ExceptionHttpRestPutRequestFailedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQ message queue is not found. Message queue name: {0}..
        /// </summary>
        internal static string ExceptionMessageQueueIsNotFound {
            get {
                return ResourceManager.GetString("ExceptionMessageQueueIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content parser implementation type found for the specified content type. Content type: {0}.
        /// </summary>
        internal static string ExceptionNoContentParserImplementationFound {
            get {
                return ResourceManager.GetString("ExceptionNoContentParserImplementationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Calling {0} an exception occured:
        ///
        ///{1}
        ///{2}.
        /// </summary>
        internal static string ExceptionOccured {
            get {
                return ResourceManager.GetString("ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counter category is not set up..
        /// </summary>
        internal static string ExceptionPerformanceCounterCategoryNotSetUp {
            get {
                return ResourceManager.GetString("ExceptionPerformanceCounterCategoryNotSetUp", resourceCulture);
            }
        }
    }
}
