//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceServer.Simulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceServer.Simulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.1.2/GatewayService.
        /// </summary>
        internal static string CfgGatewayServiceUrl {
            get {
                return ResourceManager.GetString("CfgGatewayServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading device configuration from removable media..
        /// </summary>
        internal static string ErrorFailedLoadingConfigFileFromRemovableMedia {
            get {
                return ResourceManager.GetString("ErrorFailedLoadingConfigFileFromRemovableMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed while refreshing device registration..
        /// </summary>
        internal static string ErrorFailedRefsreshingDeviceRegistration {
            get {
                return ResourceManager.GetString("ErrorFailedRefsreshingDeviceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed while refreshing the device&apos;s sensors registration..
        /// </summary>
        internal static string ErrorFailedRefsreshingDeviceSensorsRegistration {
            get {
                return ResourceManager.GetString("ErrorFailedRefsreshingDeviceSensorsRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sending sensor data over CNDEP. 
        ///Error: {0} .
        /// </summary>
        internal static string ErrorFailedSendingSensorDataOverCndep {
            get {
                return ResourceManager.GetString("ErrorFailedSendingSensorDataOverCndep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sending sensor data over HTTP. .
        /// </summary>
        internal static string ErrorFailedSendingSensorDataOverHttp {
            get {
                return ResourceManager.GetString("ErrorFailedSendingSensorDataOverHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sensor configuration found. Id: {0}.
        /// </summary>
        internal static string ErrorNoSensorConfigurationFound {
            get {
                return ResourceManager.GetString("ErrorNoSensorConfigurationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PULL sensor data retrieval mode is not supported..
        /// </summary>
        internal static string ErrorPullModeNotSupported {
            get {
                return ResourceManager.GetString("ErrorPullModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor is not found. Id: {0}.
        /// </summary>
        internal static string ErrorSensorNotFound {
            get {
                return ResourceManager.GetString("ErrorSensorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the sensor&apos;s value is not supported. Id: {0}.
        /// </summary>
        internal static string ErrorSettingSensorValueNotSupported {
            get {
                return ResourceManager.GetString("ErrorSettingSensorValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to refresh device registration. No ServerUrl specified in the device configuration..
        /// </summary>
        internal static string ErrorUnableRefreshDeviceRegistrationNoServerUrl {
            get {
                return ResourceManager.GetString("ErrorUnableRefreshDeviceRegistrationNoServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported response content type. Content type: {0}..
        /// </summary>
        internal static string ErrorUnsupportedResponseContentType {
            get {
                return ResourceManager.GetString("ErrorUnsupportedResponseContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not provided in the request..
        /// </summary>
        internal static string ErrorValueNotProvidedInRequest {
            get {
                return ResourceManager.GetString("ErrorValueNotProvidedInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content parser type is not found. Type name: {0}..
        /// </summary>
        internal static string ExceptionContentParserTypeNotFound {
            get {
                return ResourceManager.GetString("ExceptionContentParserTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content type is not supported. Type: {0}.
        /// </summary>
        internal static string ExceptionContentTypeNotSupported {
            get {
                return ResourceManager.GetString("ExceptionContentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed parsing JSON OperationResult. Content: {0}..
        /// </summary>
        internal static string ExceptionFailedParsingJsonOperationResult {
            get {
                return ResourceManager.GetString("ExceptionFailedParsingJsonOperationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed setting up sensor ports..
        /// </summary>
        internal static string ExceptionFailedSettingUpSensorPorts {
            get {
                return ResourceManager.GetString("ExceptionFailedSettingUpSensorPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete JSON DeviceConfig data. Missing property: {0}.
        /// </summary>
        internal static string ExceptionMissingJSONDeviceConfigProperty {
            get {
                return ResourceManager.GetString("ExceptionMissingJSONDeviceConfigProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete JSON SensorConfig data. Missing property: {0}.
        /// </summary>
        internal static string ExceptionMissingJSONSensorConfigProperty {
            get {
                return ResourceManager.GetString("ExceptionMissingJSONSensorConfigProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication type is not supported. Type: {0}..
        /// </summary>
        internal static string ExceptionServerCommTypeNotSupported {
            get {
                return ResourceManager.GetString("ExceptionServerCommTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type instantiation failed. Error: {0}..
        /// </summary>
        internal static string ExceptionTypeInstantiationFailed {
            get {
                return ResourceManager.GetString("ExceptionTypeInstantiationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not found. Name: {0}..
        /// </summary>
        internal static string ExceptionTypeNotFound {
            get {
                return ResourceManager.GetString("ExceptionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  HTTP response status: {0}.
        /// </summary>
        internal static string HttpResponseStatus {
            get {
                return ResourceManager.GetString("HttpResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  HTTP response status: {0}; Message: {1}.
        /// </summary>
        internal static string HttpResponseStatusWithMessage {
            get {
                return ResourceManager.GetString("HttpResponseStatusWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result returned..
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket status: {0}; Message: {1}.
        /// </summary>
        internal static string SocketStatusWithMessage {
            get {
                return ResourceManager.GetString("SocketStatusWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World!.
        /// </summary>
        internal static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
    }
}
