//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValueManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValueManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed adding value definition. Internal id: {0}. ähnelt.
        /// </summary>
        internal static string ErrorAddingValueDefinition {
            get {
                return ResourceManager.GetString("ErrorAddingValueDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The callback named {0} could not be found in the list of callbacks ähnelt.
        /// </summary>
        internal static string ErrorCallbackNameNotFound {
            get {
                return ResourceManager.GetString("ErrorCallbackNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The callback type {0} is not supported ähnelt.
        /// </summary>
        internal static string ErrorCallbackTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorCallbackTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error calling C# interactive callback. Method name: {0}; Error: {1}. ähnelt.
        /// </summary>
        internal static string ErrorCallingCSharpInteractiveCallback {
            get {
                return ResourceManager.GetString("ErrorCallingCSharpInteractiveCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error calling F# interactive callback. Method name: {0}; Error: {1}. ähnelt.
        /// </summary>
        internal static string ErrorCallingFSharpInteractiveCallback {
            get {
                return ResourceManager.GetString("ErrorCallingFSharpInteractiveCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When calling the callback {0} an error occured: {1} ähnelt.
        /// </summary>
        internal static string ErrorCallingPythonCallback {
            get {
                return ResourceManager.GetString("ErrorCallingPythonCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When calling the callback {0} an error occured: {1} ähnelt.
        /// </summary>
        internal static string ErrorCallingRubyCallback {
            get {
                return ResourceManager.GetString("ErrorCallingRubyCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When calling the callback {0} an error occured: {1} ähnelt.
        /// </summary>
        internal static string ErrorCallingScriptingCallback {
            get {
                return ResourceManager.GetString("ErrorCallingScriptingCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error executing SQL interactive callback. Error: {0} ähnelt.
        /// </summary>
        internal static string ErrorCallingSqlInteractiveCallback {
            get {
                return ResourceManager.GetString("ErrorCallingSqlInteractiveCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error executing SQL stored procedure callback. Error: {0} ähnelt.
        /// </summary>
        internal static string ErrorCallingSqlStoredProcedureCallback {
            get {
                return ResourceManager.GetString("ErrorCallingSqlStoredProcedureCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compile error:  ähnelt.
        /// </summary>
        internal static string ErrorCompileError {
            get {
                return ResourceManager.GetString("ErrorCompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating C#-interactive callback. ähnelt.
        /// </summary>
        internal static string ErrorCreatingCSharpInteractiveCallback {
            get {
                return ResourceManager.GetString("ErrorCreatingCSharpInteractiveCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating Python callback ähnelt.
        /// </summary>
        internal static string ErrorCreatingPythonCallback {
            get {
                return ResourceManager.GetString("ErrorCreatingPythonCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating Ruby callback ähnelt.
        /// </summary>
        internal static string ErrorCreatingRubyCallback {
            get {
                return ResourceManager.GetString("ErrorCreatingRubyCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating DLR scripting callback ähnelt.
        /// </summary>
        internal static string ErrorCreatingScriptingCallback {
            get {
                return ResourceManager.GetString("ErrorCreatingScriptingCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating SQL interactive callback ähnelt.
        /// </summary>
        internal static string ErrorCreatingSqlInteractiveCallback {
            get {
                return ResourceManager.GetString("ErrorCreatingSqlInteractiveCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating SQL stored procedure callback. ähnelt.
        /// </summary>
        internal static string ErrorCreatingSqlStoredProcedureCallback {
            get {
                return ResourceManager.GetString("ErrorCreatingSqlStoredProcedureCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C# interactive callback is not compiled, no module found. ähnelt.
        /// </summary>
        internal static string ErrorCSharpInteractiveCallbackIsNotCompiled {
            get {
                return ResourceManager.GetString("ErrorCSharpInteractiveCallbackIsNotCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C# interactive callback method is not found. Method name: {0}. ähnelt.
        /// </summary>
        internal static string ErrorCSharpInteractiveCallbackMethodIsNotFound {
            get {
                return ResourceManager.GetString("ErrorCSharpInteractiveCallbackMethodIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C# interactive callback type is not found. Type name: {0}. ähnelt.
        /// </summary>
        internal static string ErrorCSharpInteractiveCallbackTypeIsNotFound {
            get {
                return ResourceManager.GetString("ErrorCSharpInteractiveCallbackTypeIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The reference is a cyclic reference and thus invalid. Base value definition internal id: {0}; dependent value definition internal id: {1}. ähnelt.
        /// </summary>
        internal static string ErrorCyclicReference {
            get {
                return ResourceManager.GetString("ErrorCyclicReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In method {0} an exception occured: {1}
        ///{2}
        ///{3} ähnelt.
        /// </summary>
        internal static string ErrorExceptionOccured {
            get {
                return ResourceManager.GetString("ErrorExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error executing callback ähnelt.
        /// </summary>
        internal static string ErrorExecuteCallback {
            get {
                return ResourceManager.GetString("ErrorExecuteCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F# interactive callback is not compiled, no module found. ähnelt.
        /// </summary>
        internal static string ErrorFSharpInteractiveCallbackIsNotCompiled {
            get {
                return ResourceManager.GetString("ErrorFSharpInteractiveCallbackIsNotCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F# interactive callback method is not found. Method name: {0}. ähnelt.
        /// </summary>
        internal static string ErrorFSharpInteractiveCallbackMethodIsNotFound {
            get {
                return ResourceManager.GetString("ErrorFSharpInteractiveCallbackMethodIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F# interactive callback type is not found. Type name: {0}. ähnelt.
        /// </summary>
        internal static string ErrorFSharpInteractiveCallbackTypeIsNotFound {
            get {
                return ResourceManager.GetString("ErrorFSharpInteractiveCallbackTypeIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error initializing C# execution environment. Error: {0} ähnelt.
        /// </summary>
        internal static string ErrorInitCSharpInteractiveEnvironment {
            get {
                return ResourceManager.GetString("ErrorInitCSharpInteractiveEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error initializing F# execution environment. Error: {0} ähnelt.
        /// </summary>
        internal static string ErrorInitFSharpInteractiveEnvironment {
            get {
                return ResourceManager.GetString("ErrorInitFSharpInteractiveEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error initializing the method call environment ähnelt.
        /// </summary>
        internal static string ErrorInitMethodCallEnvironment {
            get {
                return ResourceManager.GetString("ErrorInitMethodCallEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error initializing the scripting environment ähnelt.
        /// </summary>
        internal static string ErrorInitScriptEnvironment {
            get {
                return ResourceManager.GetString("ErrorInitScriptEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error initializing SQL execution environment. Error: {0} ähnelt.
        /// </summary>
        internal static string ErrorInitSqlExecutionEnvironment {
            get {
                return ResourceManager.GetString("ErrorInitSqlExecutionEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The necessary interface {0} is not implemented by callback {1} ähnelt.
        /// </summary>
        internal static string ErrorInterfaceNotImplemented {
            get {
                return ResourceManager.GetString("ErrorInterfaceNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The callback type {0} is invalid ähnelt.
        /// </summary>
        internal static string ErrorInvalidCallbackType {
            get {
                return ResourceManager.GetString("ErrorInvalidCallbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Callback {0} doesn&apos;t have the proper type ({1}). CallbackType.VirtualValueCalculation is needed ähnelt.
        /// </summary>
        internal static string ErrorInvalidCallbackTypeForVirtualValues {
            get {
                return ResourceManager.GetString("ErrorInvalidCallbackTypeForVirtualValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no compiled script code to execute ähnelt.
        /// </summary>
        internal static string ErrorNoCompiledCode {
            get {
                return ResourceManager.GetString("ErrorNoCompiledCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot create a dependency to the same node (self-dependency). Base value definition internal id: {0}; dependent value definition internal id: {0}. ähnelt.
        /// </summary>
        internal static string ErrorNoDependencyToSelf {
            get {
                return ResourceManager.GetString("ErrorNoDependencyToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An execution type (what to execute) must be defined ähnelt.
        /// </summary>
        internal static string ErrorNoExecutionType {
            get {
                return ResourceManager.GetString("ErrorNoExecutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No proper storage to write to exists ähnelt.
        /// </summary>
        internal static string ErrorNoProperStorageToWriteTo {
            get {
                return ResourceManager.GetString("ErrorNoProperStorageToWriteTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No script runtime present ähnelt.
        /// </summary>
        internal static string ErrorNoScriptRuntime {
            get {
                return ResourceManager.GetString("ErrorNoScriptRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No script source present ähnelt.
        /// </summary>
        internal static string ErrorNoScriptSource {
            get {
                return ResourceManager.GetString("ErrorNoScriptSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value definition is no virtual value ähnelt.
        /// </summary>
        internal static string ErrorNoVirtualValueDefinition {
            get {
                return ResourceManager.GetString("ErrorNoVirtualValueDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type {0} has no Property of name {1} ähnelt.
        /// </summary>
        internal static string ErrorPropertyIsMissingInType {
            get {
                return ResourceManager.GetString("ErrorPropertyIsMissingInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type {0} has a property {1}, but it&apos;s of the wrong type {2} instead of {3} ähnelt.
        /// </summary>
        internal static string ErrorPropertyIsOfWrongType {
            get {
                return ResourceManager.GetString("ErrorPropertyIsOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Python callback: {0} is not defined or the proper parameters are not present ähnelt.
        /// </summary>
        internal static string ErrorPythonCallbackIsNotDefined {
            get {
                return ResourceManager.GetString("ErrorPythonCallbackIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Ruby callback: {0} is not defined or the proper parameters are not present ähnelt.
        /// </summary>
        internal static string ErrorRubyCallbackIsNotDefined {
            get {
                return ResourceManager.GetString("ErrorRubyCallbackIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The DLR scripting callback: {0} is not defined or the proper parameters are not present ähnelt.
        /// </summary>
        internal static string ErrorScriptingCallbackIsNotDefined {
            get {
                return ResourceManager.GetString("ErrorScriptingCallbackIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed setting up value definition. Device id: {0}; Sensor id: {1}. ähnelt.
        /// </summary>
        internal static string ErrorSettingUpValueDefinition {
            get {
                return ResourceManager.GetString("ErrorSettingUpValueDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The software agent {0} produced no result ähnelt.
        /// </summary>
        internal static string ErrorSoftwareAgentProducedNoResult {
            get {
                return ResourceManager.GetString("ErrorSoftwareAgentProducedNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error starting the write thread ähnelt.
        /// </summary>
        internal static string ErrorStartingWriteToStorageThread {
            get {
                return ResourceManager.GetString("ErrorStartingWriteToStorageThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The supplied type {0} is no proper subclass of an Activity ähnelt.
        /// </summary>
        internal static string ErrorTypeIsNoSoftwareAgent {
            get {
                return ResourceManager.GetString("ErrorTypeIsNoSoftwareAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The key {0} for the callback to evaluate the virtual value could not be found ähnelt.
        /// </summary>
        internal static string ErrorVirtualEvalCallbackKeyNotFound {
            get {
                return ResourceManager.GetString("ErrorVirtualEvalCallbackKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error writing values to the storage ähnelt.
        /// </summary>
        internal static string ErrorWritingValues {
            get {
                return ResourceManager.GetString("ErrorWritingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculation task is already started. ähnelt.
        /// </summary>
        internal static string ExceptionCalculationTaskIsAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionCalculationTaskIsAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dependent value definition is not virtual. Internal id: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionDependentValueDefinitionIsNotVirtual {
            get {
                return ResourceManager.GetString("ExceptionDependentValueDefinitionIsNotVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed creating IDbConnection instance. Type name: {0}; Error: {1} ähnelt.
        /// </summary>
        internal static string ExceptionFailedCreateDbConnectionInstance {
            get {
                return ResourceManager.GetString("ExceptionFailedCreateDbConnectionInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed creating callback for sensor. Device id; {0}; Sensor id: {1}. ähnelt.
        /// </summary>
        internal static string ExceptionFailedCreatingCallbackForSensor {
            get {
                return ResourceManager.GetString("ExceptionFailedCreatingCallbackForSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed opening database connection. Error: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionFailedToOpenDbConnection {
            get {
                return ResourceManager.GetString("ExceptionFailedToOpenDbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No results returned from the callback&apos;s SQLquery. ähnelt.
        /// </summary>
        internal static string ExceptionNoResultsReturnedFromSqlCallbackQuery {
            get {
                return ResourceManager.GetString("ExceptionNoResultsReturnedFromSqlCallbackQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The numbers of passed parameters and parameters declared in the SQL statement do not match. ähnelt.
        /// </summary>
        internal static string ExceptionNumberOfParamsInSqlStatementIsIncorrect {
            get {
                return ResourceManager.GetString("ExceptionNumberOfParamsInSqlStatementIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown VirtualSensorDefinitionType. Value: {0} ähnelt.
        /// </summary>
        internal static string ExceptionUnknownVirtualSensorDefinitionType {
            get {
                return ResourceManager.GetString("ExceptionUnknownVirtualSensorDefinitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value Definition is already registered. Internal id: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionValueDefinitionAlreadyRegistered {
            get {
                return ResourceManager.GetString("ExceptionValueDefinitionAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value definition is not found. Internal id: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionValueDefinitionNotFound {
            get {
                return ResourceManager.GetString("ExceptionValueDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Virtual sensor has no virtual definition. Device id: {0}; Sensor id: {1} ähnelt.
        /// </summary>
        internal static string ExceptionVirtualSensorHasNoVirtualDefinition {
            get {
                return ResourceManager.GetString("ExceptionVirtualSensorHasNoVirtualDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The internal id {0} is not existant in the dictionary ähnelt.
        /// </summary>
        internal static string InternalIdNotFound {
            get {
                return ResourceManager.GetString("InternalIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For a script execution ({0}) is an invalid execution type  ähnelt.
        /// </summary>
        internal static string InvalidExecutionTypeForScriptExecution {
            get {
                return ResourceManager.GetString("InvalidExecutionTypeForScriptExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No connection string specified. ähnelt.
        /// </summary>
        internal static string NoConnectionString {
            get {
                return ResourceManager.GetString("NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No connection type full name specified. ähnelt.
        /// </summary>
        internal static string NoConnectionTypeFullName {
            get {
                return ResourceManager.GetString("NoConnectionTypeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Either execution data (code) or an external filename must be specified ähnelt.
        /// </summary>
        internal static string NoExecutionDataAndFileName {
            get {
                return ResourceManager.GetString("NoExecutionDataAndFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No return type name. ähnelt.
        /// </summary>
        internal static string NoReturnTypeName {
            get {
                return ResourceManager.GetString("NoReturnTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A symbolic name for an execution unit must be defined ähnelt.
        /// </summary>
        internal static string NoSymbolicName {
            get {
                return ResourceManager.GetString("NoSymbolicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation is not yet supported ähnelt.
        /// </summary>
        internal static string NotSupportedYet {
            get {
                return ResourceManager.GetString("NotSupportedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The support for RUBY is not yet implemented ähnelt.
        /// </summary>
        internal static string RubySupportNotImplementedYet {
            get {
                return ResourceManager.GetString("RubySupportNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Due to the retry count exceeding the configured limit objects to be saved were deleted internally to maintain a stable system ähnelt.
        /// </summary>
        internal static string SaveObjectsRemovedDueToRetry {
            get {
                return ResourceManager.GetString("SaveObjectsRemovedDueToRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script File {0} does not exist ähnelt.
        /// </summary>
        internal static string ScriptFileDoesNotExist {
            get {
                return ResourceManager.GetString("ScriptFileDoesNotExist", resourceCulture);
            }
        }
    }
}
