//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorageAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataStorageAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed while closing database connection. ähnelt.
        /// </summary>
        internal static string ErrorFailedClosingDatabaseConnection {
            get {
                return ResourceManager.GetString("ErrorFailedClosingDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed storing sensor data. ähnelt.
        /// </summary>
        internal static string ErrorFailedStoringSensorData {
            get {
                return ResourceManager.GetString("ErrorFailedStoringSensorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The storage handling class {0} could not be initialized ({1}). The system cannot be used ähnelt.
        /// </summary>
        internal static string ErrorInvalidStorageImplementationClass {
            get {
                return ResourceManager.GetString("ErrorInvalidStorageImplementationClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No storage handling class was provided. The system cannot be used ähnelt.
        /// </summary>
        internal static string ErrorNoStorageImplementationClassProvided {
            get {
                return ResourceManager.GetString("ErrorNoStorageImplementationClassProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rollback failed. ähnelt.
        /// </summary>
        internal static string ErrorRollbackFailed {
            get {
                return ResourceManager.GetString("ErrorRollbackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor {0} for Device {1} is not registered ähnelt.
        /// </summary>
        internal static string ErrorSensorIsNotRegistered {
            get {
                return ResourceManager.GetString("ErrorSensorIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Array lengths must be equal. ähnelt.
        /// </summary>
        internal static string ExceptionArrayLengthsMustBeEqual {
            get {
                return ResourceManager.GetString("ExceptionArrayLengthsMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed creating a database connection instance. ähnelt.
        /// </summary>
        internal static string ExceptionFailedCreateDatabasebConnectionInstance {
            get {
                return ResourceManager.GetString("ExceptionFailedCreateDatabasebConnectionInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed creating a database command with transaction. ähnelt.
        /// </summary>
        internal static string ExceptionFailedCreateDbCommandWithTransaction {
            get {
                return ResourceManager.GetString("ExceptionFailedCreateDbCommandWithTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to open the database connection. ähnelt.
        /// </summary>
        internal static string ExceptionFailedToOpenDatabaseConnection {
            get {
                return ResourceManager.GetString("ExceptionFailedToOpenDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQLquery failed. ähnelt.
        /// </summary>
        internal static string ExceptionSqlQueryFailed {
            get {
                return ResourceManager.GetString("ExceptionSqlQueryFailed", resourceCulture);
            }
        }
    }
}
