//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceServer.AUG
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("DeviceServer.AUG.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            SensorUnitSymbolTouchscreenButton = -17507,
            DefaultSensorCategoryName = -17046,
            DescriptionSensorTouchscreenButton = -875,
            DeviceLocationNameDefault = -421,
            DescriptionSensorTemperature = -6,
            DescriptionBoard = 368,
            SensorUnitSymbolLedStatus = 13674,
            DescriptionSensorLedStatus = 14090,
            SensorUnitSymbolTemperature = 32050,
        }
    }
}
