//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServerService.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public Devices()
        {
            this.Sensors = new HashSet<Sensors>();
        }
    
        public string Id { get; set; }
        public string Description { get; set; }
        public string IpEndPoint { get; set; }
        public string LocationName { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Elevation { get; set; }
    
        public virtual ICollection<Sensors> Sensors { get; set; }
    }
}
