//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServerService.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorData
    {
        public int Identity { get; set; }
        public int SensorId { get; set; }
        public System.DateTime TakenWhen { get; set; }
        public string Value { get; set; }
        public string CorrelationId { get; set; }
    
        public virtual Sensors Sensor { get; set; }
    }
}
