//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServerService.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensors
    {
        public Sensors()
        {
            this.SensorData = new HashSet<SensorData>();
        }
    
        public string Id { get; set; }
        public string DeviceId { get; set; }
        public int SensorId { get; set; }
        public string Description { get; set; }
        public string UnitSymbol { get; set; }
        public int SensorValueDataType { get; set; }
        public int SensorDataRetrievalMode { get; set; }
        public bool ShallSensorDataBePersisted { get; set; }
        public bool PersistDirectlyAfterChange { get; set; }
        public bool IsVirtualSensor { get; set; }
        public string SensorCategory { get; set; }
        public int SensorDataCalculationMode { get; set; }
        public int VirtualSensorDefinitionType { get; set; }
        public string VirtualSensorDefininition { get; set; }
        public int PullModeCommunicationType { get; set; }
        public string PullModeDotNetType { get; set; }
        public int PullFrequencyInSec { get; set; }
        public string DefaultValue { get; set; }
        public bool IsSynchronousPushToActuator { get; set; }
        public bool IsActuator { get; set; }
        public int PushModeCommunicationType { get; set; }
    
        public virtual Devices Device { get; set; }
        public virtual ICollection<SensorData> SensorData { get; set; }
    }
}
