//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// Name der Ursprungsdatei:
// Erstellungsdatum: 01.08.2014 19:12:28
namespace OdataConsoleConsumer.OdataConsoleConsumer
{
    
    /// <summary>
    /// Es gibt keine Kommentare für Entities im Schema.
    /// </summary>
    public partial class Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisiert ein neues Entities-Objekt.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis
        ///  in Visual Studio konfiguriert ist, von demjenigen unterscheidet, der in dem 
        /// Server-Schema angegeben ist, verwenden Sie Typemapper, um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ExperimentsModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("OdataConsoleConsumer.OdataConsoleConsumer", typeName.Substring(16)), false);
            }
            return null;
        }
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis
        ///  in Visual Studio konfiguriert ist, von demjenigen unterscheidet, der in dem 
        /// Server-Schema angegeben ist, verwenden Sie Typemapper, um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("OdataConsoleConsumer.OdataConsoleConsumer", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ExperimentsModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Devices im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Devices> Devices
        {
            get
            {
                if ((this._Devices == null))
                {
                    this._Devices = base.CreateQuery<Devices>("Devices");
                }
                return this._Devices;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Devices> _Devices;
        /// <summary>
        /// Es gibt keine Kommentare für Sensors im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Sensors> Sensors
        {
            get
            {
                if ((this._Sensors == null))
                {
                    this._Sensors = base.CreateQuery<Sensors>("Sensors");
                }
                return this._Sensors;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Sensors> _Sensors;
        /// <summary>
        /// Es gibt keine Kommentare für SensorData im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SensorData> SensorData
        {
            get
            {
                if ((this._SensorData == null))
                {
                    this._SensorData = base.CreateQuery<SensorData>("SensorData");
                }
                return this._SensorData;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SensorData> _SensorData;
        /// <summary>
        /// Es gibt keine Kommentare für Devices im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDevices(Devices devices)
        {
            base.AddObject("Devices", devices);
        }
        /// <summary>
        /// Es gibt keine Kommentare für Sensors im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSensors(Sensors sensors)
        {
            base.AddObject("Sensors", sensors);
        }
        /// <summary>
        /// Es gibt keine Kommentare für SensorData im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSensorData(SensorData sensorData)
        {
            base.AddObject("SensorData", sensorData);
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für ExperimentsModel.Devices im Schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Devices")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Devices : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues Devices-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Devices CreateDevices(string ID)
        {
            Devices devices = new Devices();
            devices.Id = ID;
            return devices;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Description im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft IpEndPoint im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IpEndPoint
        {
            get
            {
                return this._IpEndPoint;
            }
            set
            {
                this.OnIpEndPointChanging(value);
                this._IpEndPoint = value;
                this.OnIpEndPointChanged();
                this.OnPropertyChanged("IpEndPoint");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IpEndPoint;
        partial void OnIpEndPointChanging(string value);
        partial void OnIpEndPointChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft LocationName im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LocationName
        {
            get
            {
                return this._LocationName;
            }
            set
            {
                this.OnLocationNameChanging(value);
                this._LocationName = value;
                this.OnLocationNameChanged();
                this.OnPropertyChanged("LocationName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LocationName;
        partial void OnLocationNameChanging(string value);
        partial void OnLocationNameChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Latitude im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this._Latitude = value;
                this.OnLatitudeChanged();
                this.OnPropertyChanged("Latitude");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Latitude;
        partial void OnLatitudeChanging(global::System.Nullable<decimal> value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Longitude im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this._Longitude = value;
                this.OnLongitudeChanged();
                this.OnPropertyChanged("Longitude");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Longitude;
        partial void OnLongitudeChanging(global::System.Nullable<decimal> value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Elevation im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Elevation
        {
            get
            {
                return this._Elevation;
            }
            set
            {
                this.OnElevationChanging(value);
                this._Elevation = value;
                this.OnElevationChanged();
                this.OnPropertyChanged("Elevation");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Elevation;
        partial void OnElevationChanging(global::System.Nullable<decimal> value);
        partial void OnElevationChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Sensors im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Sensors> Sensors
        {
            get
            {
                return this._Sensors;
            }
            set
            {
                this._Sensors = value;
                this.OnPropertyChanged("Sensors");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Sensors> _Sensors = new global::System.Data.Services.Client.DataServiceCollection<Sensors>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für ExperimentsModel.Sensors im Schema.
    /// </summary>
    /// <KeyProperties>
    /// SensorId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sensors")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SensorId")]
    public partial class Sensors : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues Sensors-Objekt.
        /// </summary>
        /// <param name="sensorId">Anfangswert von SensorId.</param>
        /// <param name="sensorValueDataType">Anfangswert von SensorValueDataType.</param>
        /// <param name="sensorDataRetrievalMode">Anfangswert von SensorDataRetrievalMode.</param>
        /// <param name="shallSensorDataBePersisted">Anfangswert von ShallSensorDataBePersisted.</param>
        /// <param name="persistDirectlyAfterChange">Anfangswert von PersistDirectlyAfterChange.</param>
        /// <param name="isVirtualSensor">Anfangswert von IsVirtualSensor.</param>
        /// <param name="sensorDataCalculationMode">Anfangswert von SensorDataCalculationMode.</param>
        /// <param name="virtualSensorDefinitionType">Anfangswert von VirtualSensorDefinitionType.</param>
        /// <param name="pullModeCommunicationType">Anfangswert von PullModeCommunicationType.</param>
        /// <param name="pullFrequencyInSec">Anfangswert von PullFrequencyInSec.</param>
        /// <param name="isSynchronousPushToActuator">Anfangswert von IsSynchronousPushToActuator.</param>
        /// <param name="isActuator">Anfangswert von IsActuator.</param>
        /// <param name="pushModeCommunicationType">Anfangswert von PushModeCommunicationType.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Sensors CreateSensors(int sensorId, int sensorValueDataType, int sensorDataRetrievalMode, bool shallSensorDataBePersisted, bool persistDirectlyAfterChange, bool isVirtualSensor, int sensorDataCalculationMode, int virtualSensorDefinitionType, int pullModeCommunicationType, int pullFrequencyInSec, bool isSynchronousPushToActuator, bool isActuator, int pushModeCommunicationType)
        {
            Sensors sensors = new Sensors();
            sensors.SensorId = sensorId;
            sensors.SensorValueDataType = sensorValueDataType;
            sensors.SensorDataRetrievalMode = sensorDataRetrievalMode;
            sensors.ShallSensorDataBePersisted = shallSensorDataBePersisted;
            sensors.PersistDirectlyAfterChange = persistDirectlyAfterChange;
            sensors.IsVirtualSensor = isVirtualSensor;
            sensors.SensorDataCalculationMode = sensorDataCalculationMode;
            sensors.VirtualSensorDefinitionType = virtualSensorDefinitionType;
            sensors.PullModeCommunicationType = pullModeCommunicationType;
            sensors.PullFrequencyInSec = pullFrequencyInSec;
            sensors.IsSynchronousPushToActuator = isSynchronousPushToActuator;
            sensors.IsActuator = isActuator;
            sensors.PushModeCommunicationType = pushModeCommunicationType;
            return sensors;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft DeviceId im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DeviceId
        {
            get
            {
                return this._DeviceId;
            }
            set
            {
                this.OnDeviceIdChanging(value);
                this._DeviceId = value;
                this.OnDeviceIdChanged();
                this.OnPropertyChanged("DeviceId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DeviceId;
        partial void OnDeviceIdChanging(string value);
        partial void OnDeviceIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SensorId im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SensorId
        {
            get
            {
                return this._SensorId;
            }
            set
            {
                this.OnSensorIdChanging(value);
                this._SensorId = value;
                this.OnSensorIdChanged();
                this.OnPropertyChanged("SensorId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SensorId;
        partial void OnSensorIdChanging(int value);
        partial void OnSensorIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Description im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft UnitSymbol im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UnitSymbol
        {
            get
            {
                return this._UnitSymbol;
            }
            set
            {
                this.OnUnitSymbolChanging(value);
                this._UnitSymbol = value;
                this.OnUnitSymbolChanged();
                this.OnPropertyChanged("UnitSymbol");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UnitSymbol;
        partial void OnUnitSymbolChanging(string value);
        partial void OnUnitSymbolChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SensorValueDataType im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SensorValueDataType
        {
            get
            {
                return this._SensorValueDataType;
            }
            set
            {
                this.OnSensorValueDataTypeChanging(value);
                this._SensorValueDataType = value;
                this.OnSensorValueDataTypeChanged();
                this.OnPropertyChanged("SensorValueDataType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SensorValueDataType;
        partial void OnSensorValueDataTypeChanging(int value);
        partial void OnSensorValueDataTypeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SensorDataRetrievalMode im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SensorDataRetrievalMode
        {
            get
            {
                return this._SensorDataRetrievalMode;
            }
            set
            {
                this.OnSensorDataRetrievalModeChanging(value);
                this._SensorDataRetrievalMode = value;
                this.OnSensorDataRetrievalModeChanged();
                this.OnPropertyChanged("SensorDataRetrievalMode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SensorDataRetrievalMode;
        partial void OnSensorDataRetrievalModeChanging(int value);
        partial void OnSensorDataRetrievalModeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft ShallSensorDataBePersisted im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool ShallSensorDataBePersisted
        {
            get
            {
                return this._ShallSensorDataBePersisted;
            }
            set
            {
                this.OnShallSensorDataBePersistedChanging(value);
                this._ShallSensorDataBePersisted = value;
                this.OnShallSensorDataBePersistedChanged();
                this.OnPropertyChanged("ShallSensorDataBePersisted");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ShallSensorDataBePersisted;
        partial void OnShallSensorDataBePersistedChanging(bool value);
        partial void OnShallSensorDataBePersistedChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft PersistDirectlyAfterChange im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool PersistDirectlyAfterChange
        {
            get
            {
                return this._PersistDirectlyAfterChange;
            }
            set
            {
                this.OnPersistDirectlyAfterChangeChanging(value);
                this._PersistDirectlyAfterChange = value;
                this.OnPersistDirectlyAfterChangeChanged();
                this.OnPropertyChanged("PersistDirectlyAfterChange");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _PersistDirectlyAfterChange;
        partial void OnPersistDirectlyAfterChangeChanging(bool value);
        partial void OnPersistDirectlyAfterChangeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft IsVirtualSensor im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsVirtualSensor
        {
            get
            {
                return this._IsVirtualSensor;
            }
            set
            {
                this.OnIsVirtualSensorChanging(value);
                this._IsVirtualSensor = value;
                this.OnIsVirtualSensorChanged();
                this.OnPropertyChanged("IsVirtualSensor");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsVirtualSensor;
        partial void OnIsVirtualSensorChanging(bool value);
        partial void OnIsVirtualSensorChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SensorCategory im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SensorCategory
        {
            get
            {
                return this._SensorCategory;
            }
            set
            {
                this.OnSensorCategoryChanging(value);
                this._SensorCategory = value;
                this.OnSensorCategoryChanged();
                this.OnPropertyChanged("SensorCategory");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SensorCategory;
        partial void OnSensorCategoryChanging(string value);
        partial void OnSensorCategoryChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SensorDataCalculationMode im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SensorDataCalculationMode
        {
            get
            {
                return this._SensorDataCalculationMode;
            }
            set
            {
                this.OnSensorDataCalculationModeChanging(value);
                this._SensorDataCalculationMode = value;
                this.OnSensorDataCalculationModeChanged();
                this.OnPropertyChanged("SensorDataCalculationMode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SensorDataCalculationMode;
        partial void OnSensorDataCalculationModeChanging(int value);
        partial void OnSensorDataCalculationModeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft VirtualSensorDefinitionType im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int VirtualSensorDefinitionType
        {
            get
            {
                return this._VirtualSensorDefinitionType;
            }
            set
            {
                this.OnVirtualSensorDefinitionTypeChanging(value);
                this._VirtualSensorDefinitionType = value;
                this.OnVirtualSensorDefinitionTypeChanged();
                this.OnPropertyChanged("VirtualSensorDefinitionType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _VirtualSensorDefinitionType;
        partial void OnVirtualSensorDefinitionTypeChanging(int value);
        partial void OnVirtualSensorDefinitionTypeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft VirtualSensorDefininition im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VirtualSensorDefininition
        {
            get
            {
                return this._VirtualSensorDefininition;
            }
            set
            {
                this.OnVirtualSensorDefininitionChanging(value);
                this._VirtualSensorDefininition = value;
                this.OnVirtualSensorDefininitionChanged();
                this.OnPropertyChanged("VirtualSensorDefininition");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VirtualSensorDefininition;
        partial void OnVirtualSensorDefininitionChanging(string value);
        partial void OnVirtualSensorDefininitionChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft PullModeCommunicationType im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PullModeCommunicationType
        {
            get
            {
                return this._PullModeCommunicationType;
            }
            set
            {
                this.OnPullModeCommunicationTypeChanging(value);
                this._PullModeCommunicationType = value;
                this.OnPullModeCommunicationTypeChanged();
                this.OnPropertyChanged("PullModeCommunicationType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PullModeCommunicationType;
        partial void OnPullModeCommunicationTypeChanging(int value);
        partial void OnPullModeCommunicationTypeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft PullModeDotNetType im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PullModeDotNetType
        {
            get
            {
                return this._PullModeDotNetType;
            }
            set
            {
                this.OnPullModeDotNetTypeChanging(value);
                this._PullModeDotNetType = value;
                this.OnPullModeDotNetTypeChanged();
                this.OnPropertyChanged("PullModeDotNetType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PullModeDotNetType;
        partial void OnPullModeDotNetTypeChanging(string value);
        partial void OnPullModeDotNetTypeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft PullFrequencyInSec im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PullFrequencyInSec
        {
            get
            {
                return this._PullFrequencyInSec;
            }
            set
            {
                this.OnPullFrequencyInSecChanging(value);
                this._PullFrequencyInSec = value;
                this.OnPullFrequencyInSecChanged();
                this.OnPropertyChanged("PullFrequencyInSec");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PullFrequencyInSec;
        partial void OnPullFrequencyInSecChanging(int value);
        partial void OnPullFrequencyInSecChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft DefaultValue im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DefaultValue
        {
            get
            {
                return this._DefaultValue;
            }
            set
            {
                this.OnDefaultValueChanging(value);
                this._DefaultValue = value;
                this.OnDefaultValueChanged();
                this.OnPropertyChanged("DefaultValue");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DefaultValue;
        partial void OnDefaultValueChanging(string value);
        partial void OnDefaultValueChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft IsSynchronousPushToActuator im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsSynchronousPushToActuator
        {
            get
            {
                return this._IsSynchronousPushToActuator;
            }
            set
            {
                this.OnIsSynchronousPushToActuatorChanging(value);
                this._IsSynchronousPushToActuator = value;
                this.OnIsSynchronousPushToActuatorChanged();
                this.OnPropertyChanged("IsSynchronousPushToActuator");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsSynchronousPushToActuator;
        partial void OnIsSynchronousPushToActuatorChanging(bool value);
        partial void OnIsSynchronousPushToActuatorChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft IsActuator im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsActuator
        {
            get
            {
                return this._IsActuator;
            }
            set
            {
                this.OnIsActuatorChanging(value);
                this._IsActuator = value;
                this.OnIsActuatorChanged();
                this.OnPropertyChanged("IsActuator");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsActuator;
        partial void OnIsActuatorChanging(bool value);
        partial void OnIsActuatorChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft PushModeCommunicationType im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PushModeCommunicationType
        {
            get
            {
                return this._PushModeCommunicationType;
            }
            set
            {
                this.OnPushModeCommunicationTypeChanging(value);
                this._PushModeCommunicationType = value;
                this.OnPushModeCommunicationTypeChanged();
                this.OnPropertyChanged("PushModeCommunicationType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PushModeCommunicationType;
        partial void OnPushModeCommunicationTypeChanging(int value);
        partial void OnPushModeCommunicationTypeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Device im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Devices Device
        {
            get
            {
                return this._Device;
            }
            set
            {
                this._Device = value;
                this.OnPropertyChanged("Device");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Devices _Device;
        /// <summary>
        /// Es gibt keine Kommentare für SensorData im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SensorData> SensorData
        {
            get
            {
                return this._SensorData;
            }
            set
            {
                this._SensorData = value;
                this.OnPropertyChanged("SensorData");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SensorData> _SensorData = new global::System.Data.Services.Client.DataServiceCollection<SensorData>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für ExperimentsModel.SensorData im Schema.
    /// </summary>
    /// <KeyProperties>
    /// Identity
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SensorData")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Identity")]
    public partial class SensorData : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues SensorData-Objekt.
        /// </summary>
        /// <param name="identity">Anfangswert von Identity.</param>
        /// <param name="sensorId">Anfangswert von SensorId.</param>
        /// <param name="takenWhen">Anfangswert von TakenWhen.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SensorData CreateSensorData(int identity, int sensorId, global::System.DateTime takenWhen)
        {
            SensorData sensorData = new SensorData();
            sensorData.Identity = identity;
            sensorData.SensorId = sensorId;
            sensorData.TakenWhen = takenWhen;
            return sensorData;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Identity im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("Identity");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Identity;
        partial void OnIdentityChanging(int value);
        partial void OnIdentityChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SensorId im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SensorId
        {
            get
            {
                return this._SensorId;
            }
            set
            {
                this.OnSensorIdChanging(value);
                this._SensorId = value;
                this.OnSensorIdChanged();
                this.OnPropertyChanged("SensorId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SensorId;
        partial void OnSensorIdChanging(int value);
        partial void OnSensorIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft TakenWhen im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime TakenWhen
        {
            get
            {
                return this._TakenWhen;
            }
            set
            {
                this.OnTakenWhenChanging(value);
                this._TakenWhen = value;
                this.OnTakenWhenChanged();
                this.OnPropertyChanged("TakenWhen");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _TakenWhen;
        partial void OnTakenWhenChanging(global::System.DateTime value);
        partial void OnTakenWhenChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Value im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft CorrelationId im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CorrelationId
        {
            get
            {
                return this._CorrelationId;
            }
            set
            {
                this.OnCorrelationIdChanging(value);
                this._CorrelationId = value;
                this.OnCorrelationIdChanged();
                this.OnPropertyChanged("CorrelationId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CorrelationId;
        partial void OnCorrelationIdChanging(string value);
        partial void OnCorrelationIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Sensor im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Sensors Sensor
        {
            get
            {
                return this._Sensor;
            }
            set
            {
                this._Sensor = value;
                this.OnPropertyChanged("Sensor");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Sensors _Sensor;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
