//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://namespaces.cconsult.lv", ConfigurationName="IInfoWcfService")]
public interface IInfoWcfService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:#FindInfosAfterDate", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
    FindInfosAfterDateResult FindInfosAfterDate(System.DateTime afterDater, int maxRows);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:#FindInforsAfterDate_Local", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
    FindInfosAfterDateResult FindInfosAfterDate_Local(System.DateTime afterDater, int maxRows);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespaces.cconsult.lv")]
public partial class FindInfosAfterDateResult
{
    
    private InfoWcfElement[] infoElementsField;
    
    private int resultStatusField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Element", IsNullable=false)]
    public InfoWcfElement[] infoElements
    {
        get
        {
            return this.infoElementsField;
        }
        set
        {
            this.infoElementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int resultStatus
    {
        get
        {
            return this.resultStatusField;
        }
        set
        {
            this.resultStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string errorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespaces.cconsult.lv")]
public partial class InfoWcfElement
{
    
    private System.DateTime createdField;
    
    private string applicationField;
    
    private string infoField;
    
    private sbyte levelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime created
    {
        get
        {
            return this.createdField;
        }
        set
        {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string application
    {
        get
        {
            return this.applicationField;
        }
        set
        {
            this.applicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string info
    {
        get
        {
            return this.infoField;
        }
        set
        {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public sbyte level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IInfoWcfServiceChannel : IInfoWcfService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InfoWcfServiceClient : System.ServiceModel.ClientBase<IInfoWcfService>, IInfoWcfService
{
    
    public InfoWcfServiceClient()
    {
    }
    
    public InfoWcfServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InfoWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InfoWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InfoWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FindInfosAfterDateResult FindInfosAfterDate(System.DateTime afterDater, int maxRows)
    {
        return base.Channel.FindInfosAfterDate(afterDater, maxRows);
    }
    
    public FindInfosAfterDateResult FindInfosAfterDate_Local(System.DateTime afterDater, int maxRows)
    {
        return base.Channel.FindInfosAfterDate_Local(afterDater, maxRows);
    }
}
